# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  config.vm.box = "puppetlabs/centos-7.2-64-puppet"
  config.vm.provision "shell", inline: "/opt/puppetlabs/bin/puppet apply --modulepath /vagrant/manifests /vagrant/manifests/d3r_open.pp"
  #config.vm.provision "puppet" do |puppet|
  #  puppet.manifests_path = "manifests"
  #  puppet.manifest_file = "d3r_open.pp"
  #  puppet.options = "--verbose --debug"
  #end
  config.ssh.forward_x11 = true  
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = "1"
  end
end
